### ISSUE TITLE
Cascaded click?

### ISSUE THREAD

**Issue by gplesz** [MisterJames/CollidR#10]
![collidr](https://f.cloud.github.com/assets/3380797/1225458/790cd29c-2768-11e3-91ab-6b4881ba9f1e.png)

If i use 3 page, and i click on first page, then the second page of the message arrives, set of the focus, then on the third page of the message is received as if it would happen on the second page of the edit

**Comment by MisterJames** [comment]
I'm not sure I follow there with the diagram, but I think I understand what you're saying. I'll have a look into this one too.

**Comment by gplesz** [comment]
Super!:)

**Comment by MisterJames** [comment]
Ah...got it. I see the browsers aren't playing nicely :)

My best guess here is that when I add the tooltip on one of the not-in-focus forms that it is causing a focus on the field. It gets a little more trippy still if you start switching up browsers. I'll have to keep investigating, and more importantly, test on multiple machines.

**Comment by MisterJames** [comment]
I have implemented a "stringDictionary" library that should make this easier to diagnose, but haven't got back to it. It's still happening, for sure, but I haven't confirmed what the source is.

**Comment by MisterJames** [comment]
Turns out this was a problem with the bootstrap tooltip; it doesn't (always) refresh when you update the title, so you have to call a fixTitle method on the tooltip. Thanks @gplesz for finding this one!

**Comment by gplesz** [comment]
This is really cool, I look at the new version! :+1:
