### ISSUE TITLE
Add support for String, Guid, and Int64 keys

### ISSUE THREAD

**Issue by dpaquette** [MisterJames/CollidR#29]
Current implementation only supports integer based primary keys for objects. Consider adding support for other primary key types.

**Comment by MisterJames** [comment]
Thanks Dave...this is a tough one...might have to look at that earlier than later.  SignalR doesn't support overloaded methods at this point, so I'd have to just go to strings as a default catch-all. That's not necessarily bad, but it should definitely be done before v1 as that could be a breaking change for peeps down the road.

**Comment by dpaquette** [comment]
Ah..I had not thought of the overload issue. I am thinking we should go with string based keys then. Otherwise it could be a show stopper for anyone with non-integer based keys.
